name: smartcity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  font_awesome_flutter: ^11.0.0
  url_launcher: ^6.3.2
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  flutter_inappwebview: ^6.1.5
  image_picker: ^1.2.3
  google_maps_flutter: ^2.17.1
  flutter_launcher_icons: ^0.14.4
      

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/aski_images/
    - assets/bottom_drawer_images/
    - assets/hizmet_talepleri_images/
    - assets/ihbar_sikayet_images/
    - assets/turistik_adana_images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21